name: UnknownSound
favicon: null
layout_spectrum: 0.59682
typography_spectrum: 0.25941
title: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69924507-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#322b2d'
    - '#45fffe'
    - '#b3b4b9'
    - '#707274'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
