name: Unknown Sound
favicon: null
layout_spectrum: 0.18948
typography_spectrum: 0.25941
title: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69924507-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#322b2d'
    - '#45fffe'
    - '#b3b4b9'
    - '#707274'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
