name: UnknownSound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20766
title: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020000'
    - '#e92735'
    - '#56bafb'
    - '#c892fb'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
