name: UnknownSound
favicon: null
layout_spectrum: 0.6105206478387117
typography_spectrum: 0.29955706582404673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feea3f'
    - '#231f20'
    - '#0690cf'
    - '#675e2a'
    - '#9e9131'
  brandStrength: 0.125
  lightness: 0.5466952500864863
  saturation: 0.9172776725608855
  rhythmicContrast: 0.5498097261879593
purpose: []
