name: UnknownSound
favicon: null
layout_spectrum: 0.38919
typography_spectrum: 0.20766
title: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#322b2d'
    - '#45fffe'
    - '#b3b4b9'
    - '#707274'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
