typography_spectrum: 0.5127410143613815
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5100557133555412
  lightness: 0.3024251877795905
  saturation: 0.6636671447195113
  rhythmicContrast: 0.977058264426887
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13279371522367
analytics:
  google: UA-69924507-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9e222a7-949a-4bbd-a555-60719d668d5e.png
name: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: 46a0774d-98b3-49a3-9684-2da039beae7f
    type: content
  - name: YouTube
    url: 'https://www.youtube.com/c/unknownsound'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c49c66ba-a477-4302-82c0-68bdd7f807f7.png
title: Unknown Sound
description: All the up and coming music you haven't heard of yet...
purpose: []
