name: UnknownSound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20766
title: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2ab99'
    - '#b37f96'
    - '#673f1b'
    - '#9d4c99'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
