typography_spectrum: 0.14922
color:
  brandColors:
    - '#ffffff'
    - '#322b2d'
    - '#45fffe'
    - '#b3b4b9'
    - '#707274'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7379
analytics:
  google: UA-69924507-1
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9e222a7-949a-4bbd-a555-60719d668d5e.png
name: Unknown Sound
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: 46a0774d-98b3-49a3-9684-2da039beae7f
    type: content
  - name: Contact Us
    url: 'http://unknownsound.com/contact-us'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c49c66ba-a477-4302-82c0-68bdd7f807f7.png
title: Unknown Sound
description: All the up and coming music you haven't heard of yet...
purpose: []
